/*
 * Valve.h
 *
 *  Created on: 21 apr 2022
 *      Author: William.Favaro
 */

#ifndef VALVE_H_
#define VALVE_H_



/* Originial */
#define VALVE_MODULE_STEP_1 0xC6C6
#define VALVE_MODULE_STEP_2 0x24C6
#define VALVE_MODULE_STEP_3 0xB8C6
#define VALVE_MODULE_STEP_4 0xB824
#define VALVE_MODULE_STEP_5 0xB8B8
#define VALVE_MODULE_STEP_6 0x24B8
#define VALVE_MODULE_STEP_7 0xC6B8
#define VALVE_MODULE_STEP_8 0xC624

#define VALVE_MODULE_STBY_1 0x0008
#define VALVE_MODULE_STBY_2 0x0808
#define VALVE_MODULE_STBY_3 0x0840
#define VALVE_MODULE_STBY_4 0x4048
#define VALVE_MODULE_STBY_5 0x4848
#define VALVE_MODULE_STBY_6 0x0000

/* Type M */
#define VALVE_MODULE_STEP_M_1
#define VALVE_MODULE_STEP_M_2
#define VALVE_MODULE_STEP_M_3
#define VALVE_MODULE_STEP_M_4
#define VALVE_MODULE_STEP_M_5
#define VALVE_MODULE_STEP_M_6
#define VALVE_MODULE_STEP_M_7
#define VALVE_MODULE_STEP_M_8

#define VALVE_MODULE_STBY_M_1
#define VALVE_MODULE_STBY_M_2
#define VALVE_MODULE_STBY_M_3
#define VALVE_MODULE_STBY_M_4
#define VALVE_MODULE_STBY_M_5
#define VALVE_MODULE_STBY_M_6

/* Additional Valve */
#define VALVE_MODULE_STEP_1_EXT
#define VALVE_MODULE_STEP_2_EXT
#define VALVE_MODULE_STEP_3_EXT
#define VALVE_MODULE_STEP_4_EXT
#define VALVE_MODULE_STEP_5_EXT
#define VALVE_MODULE_STEP_6_EXT
#define VALVE_MODULE_STEP_7_EXT
#define VALVE_MODULE_STEP_8_EXT

#define VALVE_MODULE_STBY_1_EXT
#define VALVE_MODULE_STBY_2_EXT
#define VALVE_MODULE_STBY_3_EXT
#define VALVE_MODULE_STBY_4_EXT
#define VALVE_MODULE_STBY_5_EXT
#define VALVE_MODULE_STBY_6_EXT

/* Martini */
#define VALVE_MODULE_STEP_W_1
#define VALVE_MODULE_STEP_W_2
#define VALVE_MODULE_STEP_W_3
#define VALVE_MODULE_STEP_W_4
#define VALVE_MODULE_STEP_W_5
#define VALVE_MODULE_STEP_W_6
#define VALVE_MODULE_STEP_W_7
#define VALVE_MODULE_STEP_W_8

#define VALVE_MODULE_STBY_W_1
#define VALVE_MODULE_STBY_W_2
#define VALVE_MODULE_STBY_W_3
#define VALVE_MODULE_STBY_W_4
#define VALVE_MODULE_STBY_W_5
#define VALVE_MODULE_STBY_W_6

/* Type W */
#define VALVE_MODULE_STEP_W_1_EXT
#define VALVE_MODULE_STEP_W_2_EXT
#define VALVE_MODULE_STEP_W_3_EXT
#define VALVE_MODULE_STEP_W_4_EXT
#define VALVE_MODULE_STEP_W_5_EXT
#define VALVE_MODULE_STEP_W_6_EXT
#define VALVE_MODULE_STEP_W_7_EXT
#define VALVE_MODULE_STEP_W_8_EXT

#define VALVE_MODULE_STBY_W_1_EXT
#define VALVE_MODULE_STBY_W_2_EXT
#define VALVE_MODULE_STBY_W_3_EXT
#define VALVE_MODULE_STBY_W_4_EXT
#define VALVE_MODULE_STBY_W_5_EXT
#define VALVE_MODULE_STBY_W_6_EXT

typedef struct{
	uint16_t Timer;
	uint8_t Cycle;
	uint32_t Module;
}ValveStruct;

#endif /* VALVE_H_ */
